# Generated by Django 6.0.7 on 2026-08-04 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_alter_organization_last_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Порядковый номер')),
                ('title', models.CharField(max_length=100, verbose_name='Название награды')),
                ('is_super', models.BooleanField(default=False, verbose_name='Супер-награда')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_steps', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Шаг анкеты',
                'verbose_name_plural': 'Шаги анкеты',
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'position'), name='unique_reward_position_per_org')],
            },
        ),
    ]
