# Generated by Django 6.0.7 on 2026-08-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardstep',
            name='is_super',
        ),
        migrations.AddField(
            model_name='rewardstep',
            name='super_reward_title',
            field=models.CharField(blank=True, help_text='Необязательно. Например: «Торт» — добавляется к основной награде на этом шаге.', max_length=100, verbose_name='Дополнительная награда'),
        ),
    ]
