# Generated by Django 6.0.7 on 2026-08-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0002_remove_rewardstep_is_super_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardstep',
            name='super_reward_title',
        ),
    ]
