# Generated by Django 6.0.7 on 2026-07-18 07:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('type', models.CharField(choices=[('FLOWER', 'Цветочный магазин'), ('CAKE', 'Кондитерская'), ('BALLOONS', 'Магазин шаров'), ('ANIMATORS', 'Аниматоры'), ('TOYS', 'Магазин игрушек'), ('RESTAURANT', 'Ресторан'), ('CAFE', 'Кафе'), ('JEWELRY', 'Ювелирный салон')], default='FLOWER', max_length=20, verbose_name='Тип')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Введите номер телефона в корректном формате', regex='^\\+?[0-9]{7,15}$')], verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('crm_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='CRM')),
                ('kassa_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Касса')),
                ('tariff', models.CharField(choices=[('BASIC', 'Базовый'), ('PREMIUM', 'Премиум')], default='BASIC', max_length=20, verbose_name='Тариф')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('last_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Последний платёж')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='referrals.referral', verbose_name='Реферал')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
    ]
