# Generated by Django 6.0.7 on 2026-07-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('FLOWER', 'Цветочный магазин'), ('CAKE', 'Кондитерская'), ('BALLOONS', 'Магазин шаров'), ('ANIMATORS', 'Аниматоры'), ('TOYS', 'Магазин игрушек'), ('RESTAURANT', 'Ресторан'), ('CAFE', 'Кафе'), ('JEWELRY', 'Ювелирный салон'), ('GAME_ROOM', 'Игровая комната'), ('QIZ', 'Клуб QIZ')], default='FLOWER', max_length=20, verbose_name='Тип'),
        ),
    ]
