# Generated by Django 6.0.7 on 2026-07-24 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='upcoming_event_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='За сколько дней до события показывать его на главной странице', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Показывать события за N дней'),
        ),
    ]
