# Generated by Django 6.0.7 on 2026-07-27 11:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_upcoming_event_days'),
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('type', models.CharField(choices=[('FLOWER', 'Цветочный магазин'), ('CAKE', 'Кондитерская'), ('BALLOONS', 'Магазин шаров'), ('ANIMATORS', 'Аниматоры'), ('TOYS', 'Магазин игрушек'), ('RESTAURANT', 'Ресторан'), ('CAFE', 'Кафе'), ('JEWELRY', 'Ювелирный салон'), ('GAME_ROOM', 'Игровая комната'), ('QIZ', 'Клуб QIZ')], default='FLOWER', max_length=20, verbose_name='Тип')),
                ('phone', models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Введите номер телефона в корректном формате', regex='^\\+?[0-9]{7,15}$')], verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('tariff', models.CharField(choices=[('BASIC', 'Базовый'), ('PREMIUM', 'Премиум')], default='BASIC', max_length=20, verbose_name='Тариф')),
                ('status', models.CharField(choices=[('PENDING', 'На рассмотрении'), ('APPROVED', 'Одобрена'), ('REJECTED', 'Отклонена')], db_index=True, default='PENDING', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, help_text='Например, причина отказа или заметки при обработке', null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработана')),
                ('organization', models.OneToOneField(blank=True, help_text='Заполняется автоматически при одобрении заявки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='organizations.organization', verbose_name='Созданная организация')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='referrals.referral', verbose_name='Реферал')),
            ],
            options={
                'verbose_name': 'Заявка на подключение',
                'verbose_name_plural': 'Заявки на подключение',
                'ordering': ['-created_at'],
            },
        ),
    ]
