# Generated by Django 6.0.7 on 2026-08-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, help_text='Обновляется автоматически из модели Payment (приложение pay)', null=True, verbose_name='Последний платёж'),
        ),
    ]
