# Generated by Django 6.0.7 on 2026-07-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telegram',
            field=models.CharField(blank=True, verbose_name='Телеграм'),
        ),
    ]
