# Generated by Django 6.0.7 on 2026-07-21 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telegram',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message='Введите корректный юзернейм Telegram (5-32 символа: латиница, цифры, подчёркивание, начинается с буквы)', regex='^@?[a-zA-Z]\\w{4,31}$')], verbose_name='Телеграм'),
        ),
    ]
