# Generated by Django 6.0.7 on 2026-07-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_archived_at_client_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notified',
            field=models.BooleanField(default=False, verbose_name='Анкета отправлена'),
        ),
    ]
