# Generated by Django 6.0.7 on 2026-08-01 09:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='anketa_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен анкеты'),
        ),
    ]
