# Generated by Django 6.0.7 on 2026-08-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_anketa_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='anketa_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Анкета завершена клиентом'),
        ),
        migrations.AddField(
            model_name='client',
            name='reward_received',
            field=models.BooleanField(default=False, verbose_name='Награда получена'),
        ),
    ]
