# Generated by Django 6.0.7 on 2026-08-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_client_anketa_completed_at_client_reward_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='earned_reward_title',
            field=models.CharField(blank=True, help_text='Фиксируется автоматически при завершении анкеты клиентом', max_length=100, verbose_name='Полученная награда'),
        ),
    ]
