# Generated by Django 6.0.7 on 2026-07-18 07:48

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=15, unique=True, validators=[accounts.validators.validate_phone], verbose_name='Телефон')),
                ('promo_code', models.CharField(max_length=20, unique=True, verbose_name='Промо-код')),
                ('percent', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Процент')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
        ),
    ]
