# Generated by Django 6.0.7 on 2026-07-18 08:01

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'verbose_name': 'Реферал', 'verbose_name_plural': 'Рефералы'},
        ),
        migrations.RemoveField(
            model_name='referral',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='promo_code',
        ),
        migrations.AddField(
            model_name='referral',
            name='commission_percent',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Комиссия (%)'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[accounts.validators.validate_phone], verbose_name='Телефон'),
        ),
    ]
