# Generated by Django 6.0.7 on 2026-07-20 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_order_updated_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_order_per_org_and_client',
        ),
    ]
