# Generated by Django 6.0.7 on 2026-07-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_archived_at_order_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Резерв'), ('PRE_PAYMENT', 'Предоплата'), ('PAID', 'Оплочено')], default='RESERVED', max_length=20, verbose_name='Статус'),
        ),
    ]
