# Generated by Django 6.0.7 on 2026-08-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Резерв'), ('PREPAYMENT', 'Предоплата'), ('PAID', 'Оплочено')], default='RESERVED', max_length=20, verbose_name='Статус'),
        ),
    ]
