# Generated by Django 6.0.7 on 2026-07-18 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('relation', models.CharField(choices=[('WIFE', 'Жена'), ('HUSBAND', 'Муж'), ('SON', 'Сын'), ('DAUGHTER', 'Дочь'), ('BOYFRIEND', 'Парень'), ('GIRLFRIEND', 'Девушка'), ('MOTHER', 'Мать'), ('FATHER', 'Отец'), ('FRIEND', 'Друг'), ('FEMALE_FRIEND', 'Подруга')], max_length=50, verbose_name='Отношение')),
                ('event_type', models.CharField(choices=[('BIRTHDAY', 'День рождения'), ('ANNIVERSARY', 'Годовщина'), ('GRADUATION', 'Выпускной'), ('HOLIDAY', 'Праздник'), ('EVENT', 'Мероприятие')], max_length=50, verbose_name='Тип события')),
                ('event_date', models.DateField(verbose_name='Дата события')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clients.client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['event_date'],
            },
        ),
    ]
