# Generated by Django 6.0.7 on 2026-07-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_archived_at_event_is_archived_event_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='proposal_sent',
            field=models.BooleanField(default=False, verbose_name='Предложение отправлено'),
        ),
        migrations.AlterField(
            model_name='event',
            name='relation',
            field=models.CharField(choices=[('WIFE', 'Жена'), ('HUSBAND', 'Муж'), ('SON', 'Сын'), ('DAUGHTER', 'Дочь'), ('BOYFRIEND', 'Парень'), ('GIRLFRIEND', 'Девушка'), ('MOTHER', 'Мать'), ('FATHER', 'Отец'), ('FRIEND', 'Друг'), ('FEMALE_FRIEND', 'Подруга'), ('PET', 'Питомец')], max_length=50, verbose_name='Отношение'),
        ),
    ]
