# Generated by Django 6.0.7 on 2026-08-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_proposal_sent_alter_event_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='relation',
            field=models.CharField(choices=[('SELF', 'Клиент'), ('WIFE', 'Жена'), ('HUSBAND', 'Муж'), ('SON', 'Сын'), ('DAUGHTER', 'Дочь'), ('BOYFRIEND', 'Парень'), ('GIRLFRIEND', 'Девушка'), ('MOTHER', 'Мать'), ('FATHER', 'Отец'), ('FRIEND', 'Друг'), ('FEMALE_FRIEND', 'Подруга'), ('PET', 'Питомец')], max_length=50, verbose_name='Отношение'),
        ),
    ]
